--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 20 2024 20:31
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Projects'   
-- project_id      :  
-- project_name    :  
-- start_date      :  
-- end_date        :  
--
CREATE TABLE Projects (
    project_id     NUMBER(38) NOT NULL,
    project_name   VARCHAR2 NOT NULL,
    start_date     DATE NOT NULL,
    end_date       DATE NOT NULL,
CONSTRAINT pk_Projects PRIMARY KEY (project_id))
/


--
-- Create Table    : 'Departments'   
-- department_id   :  
-- department_name :  
--
CREATE TABLE Departments (
    department_id  NUMBER(38) NOT NULL,
    department_name VARCHAR2 NOT NULL,
CONSTRAINT pk_Departments PRIMARY KEY (department_id))
/


--
-- Create Table    : 'Engineers'   
-- engineer_id     :  
-- first_name      :  
-- last_name       :  
-- specialty       :  
-- project_id      :  
-- hire_date       :  
--
CREATE TABLE Engineers (
    engineer_id    NUMBER(38) NOT NULL,
    first_name     VARCHAR2 NOT NULL,
    last_name      VARCHAR2 NOT NULL,
    specialty      VARCHAR2 NOT NULL,
    project_id     NUMBER(38) NOT NULL,
    hire_date      DATE NOT NULL,
CONSTRAINT pk_Engineers PRIMARY KEY (engineer_id),
CONSTRAINT fk_Engineers FOREIGN KEY (project_id)
    REFERENCES Projects (project_id))
/


--
-- Create Table    : 'SafetyOfficers'   
-- officer_id      :  
-- first_name      :  
-- last_name       :  
-- certification   :  
-- department_id   :  
-- hire_date       :  
--
CREATE TABLE SafetyOfficers (
    officer_id     NUMBER(38) NOT NULL,
    first_name     VARCHAR2(1) NOT NULL,
    last_name      VARCHAR2(1) NOT NULL,
    certification  VARCHAR2(1) NOT NULL,
    department_id  NUMBER(38) NOT NULL,
    hire_date      DATE NOT NULL,
CONSTRAINT pk_SafetyOfficers PRIMARY KEY (officer_id),
CONSTRAINT fk_SafetyOfficers FOREIGN KEY (department_id)
    REFERENCES Departments (department_id))
/


--
-- Create Table    : 'ProjectManagers'   
-- manager_id      :  
-- first_name      :  
-- last_name       :  
-- project_id      :  
-- department_id   :  
-- hire_date       :  
--
CREATE TABLE ProjectManagers (
    manager_id     NUMBER(38) NOT NULL,
    first_name     VARCHAR2 NOT NULL,
    last_name      VARCHAR2 NOT NULL,
    project_id     NUMBER(38) NOT NULL,
    department_id  NUMBER(38) NOT NULL,
    hire_date      DATE NOT NULL,
CONSTRAINT pk_ProjectManagers PRIMARY KEY (manager_id),
CONSTRAINT fk_ProjectManagers FOREIGN KEY (department_id)
    REFERENCES Departments (department_id),
CONSTRAINT fk_ProjectManagers2 FOREIGN KEY (project_id)
    REFERENCES Projects (project_id))
/


--
-- Create Table    : 'OfficeTechnicians'   
-- technician_id   :  
-- first_name      :  
-- last_name       :  
-- supervisor_id   :  
-- hire_date       :  
-- manager_id      :  (references ProjectManagers.manager_id)
--
CREATE TABLE OfficeTechnicians (
    technician_id  NUMBER(38) NOT NULL,
    first_name     VARCHAR2(1) NOT NULL,
    last_name      VARCHAR2(1) NOT NULL,
    supervisor_id  NUMBER(38) NOT NULL,
    hire_date      DATE NOT NULL,
    manager_id     NUMBER(38),
CONSTRAINT pk_OfficeTechnicians PRIMARY KEY (technician_id),
CONSTRAINT fk_OfficeTechnicians FOREIGN KEY (manager_id)
    REFERENCES ProjectManagers (manager_id))
/


--
-- Permissions for: 'public'
--
GRANT ALL ON Projects TO public
/
GRANT ALL ON Departments TO public
/
GRANT ALL ON Engineers TO public
/
GRANT ALL ON SafetyOfficers TO public
/
GRANT ALL ON ProjectManagers TO public
/
GRANT ALL ON OfficeTechnicians TO public
/

exit;

